/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import unt.herrera.prog2.tp7.gui.personas.modelos.Alumno;

import Gestor.GestorTrabajo;
import static Gestor.GestorTrabajo.Cotutor;
import static Gestor.GestorTrabajo.Jurado;
import static Gestor.GestorTrabajo.Profesores;
import static Gestor.GestorTrabajo.Tutor;
import Datos.Trabajo;
import static Gestor.GestorTrabajo.Alumno;
import static Gestor.GestorTrabajo.alumnos;
import static Gestor.GestorTrabajo.cotutores;
import static Gestor.GestorTrabajo.jurados;
import static Gestor.GestorTrabajo.profesores;
import static Gestor.GestorTrabajo.tutores;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import unt.herrera.prog2.tp7.gui.personas.modelos.Profesor;

/**
 *
 * @author joaquin
 */
public class Frm_GuardarDatos extends javax.swing.JFrame {

    GestorTrabajo gt = new GestorTrabajo();
    Trabajo trabajo = new Trabajo();

    public void activaDesactiva(boolean accion) {
//        txtTitulo.setEditable(accion);
//        txtDuracion.setEditable(accion);
//        txtArea.setEditable(accion);
//        txtTitulo.requestFocus();
    }

    public void limpiar() {
        txtTitulo.setText("");
        txtDuracion.setText("");
        txtArea.setText("");
        txtTitulo.requestFocus();
    }

    public Frm_GuardarDatos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagen/birrete (2).png")).getImage());
        this.setLocationRelativeTo(null);
//        this.setExtendedState(Frm_GuardarDatos.MAXIMIZED_HORIZ);
        ImageIcon nuevo = new ImageIcon(getClass().getResource("/imagen/fondonaranja1.jpg"));
        ImageIcon icono = new ImageIcon(nuevo.getImage().getScaledInstance(jLabel20.getWidth(), jLabel20.getHeight(), Image.SCALE_DEFAULT));
        jLabel20.setIcon(icono);
        jLabel20.setVisible(true);
//        ImageIcon nuevo2 = new ImageIcon (getClass().getResource("/imagen/BOTON-CERRAR.png"));
//        ImageIcon icono2 = new ImageIcon(nuevo2.getImage().getScaledInstance(btnSalir.getWidth(), btnSalir.getHeight(), Image.SCALE_DEFAULT));
//        btnSalir.setIcon(icono2);
//        btnSalir.setVisible(true);
        int x = 0;
        if (x == 0) {
            Jurado(comboJurado);
            Profesores(comboProfesor);
            Tutor(comboTutor);
            Cotutor(comboCotutor);
            Alumno(comboAlumno);
        }
        txtAgProf.setVisible(false);
        txtAgAlumno.setVisible(false);
        txtAgCotutor.setVisible(false);
        txtAgTutor.setVisible(false);
        txtAgJurado.setVisible(false);
        txtApAlumno.setVisible(false);
        txtApCotutor.setVisible(false);
        txtApTutor.setVisible(false);
        txtApProf.setVisible(false);
        txtApJurado.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
//        btnAtras.setVisible(false);
//        fechaEx.setEnabled(false);
        cerrar();
        x = 1;
    }

    public void cerrar() {
        try {
            this.setDefaultCloseOperation(Frm_GuardarDatos.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();

//            frame1.setVisible(false);
                }
            });
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(null, "Esta seguro de volver al menu principal?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION);

        if (valor == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            JFrame frame = new Frm_Opciones();

            frame.setLocationRelativeTo(frame);
            frame.setVisible(true);
            this.hide();
//            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Duracion = new javax.swing.JLabel();
        Area = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboTutor = new javax.swing.JComboBox<>();
        comboCotutor = new javax.swing.JComboBox<>();
        comboJurado = new javax.swing.JComboBox<>();
        comboAlumno = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboProfesor = new javax.swing.JComboBox<>();
        btnAgregarProfesor = new javax.swing.JButton();
        txtAgProf = new javax.swing.JTextField();
        btnAgregarTutor = new javax.swing.JButton();
        btnAgregarCotutor = new javax.swing.JButton();
        btnAgregarJurado = new javax.swing.JButton();
        btnAgregarAlumno = new javax.swing.JButton();
        txtAgTutor = new javax.swing.JTextField();
        txtAgCotutor = new javax.swing.JTextField();
        txtAgJurado = new javax.swing.JTextField();
        txtAgAlumno = new javax.swing.JTextField();
        txtApProf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtApTutor = new javax.swing.JTextField();
        txtApCotutor = new javax.swing.JTextField();
        txtApJurado = new javax.swing.JTextField();
        txtApAlumno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fechaPre = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        fechaAp = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        fechaEx = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Trabajo");
        setBackground(new java.awt.Color(102, 204, 0));
        setExtendedState(6);
        setMaximumSize(new java.awt.Dimension(760, 440));
        setMinimumSize(new java.awt.Dimension(760, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Titulo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 77, 20));

        Duracion.setText("Duracion");
        getContentPane().add(Duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 77, -1));

        Area.setText("Area");
        getContentPane().add(Area, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 59, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 158, 25));

        txtDuracion.setToolTipText("");
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 158, 25));
        getContentPane().add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 158, 25));

        btnGuardar.setBackground(new java.awt.Color(0, 102, 102));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 110, 30));

        btnSalir.setBackground(new java.awt.Color(153, 0, 0));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Volver");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 110, 30));

        jLabel5.setText("Tutor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 49, -1));

        jLabel6.setText("Cotutor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 51, -1));

        jLabel7.setText("Jurado");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 50, 20));

        jLabel8.setText("Alumno");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 50, -1));
        getContentPane().add(comboTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 130, -1));
        getContentPane().add(comboCotutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 130, -1));
        getContentPane().add(comboJurado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 130, -1));
        getContentPane().add(comboAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 130, -1));

        jLabel9.setText("Profesor");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 78, -1));
        getContentPane().add(comboProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 130, -1));

        btnAgregarProfesor.setText("Agregar Profesor");
        btnAgregarProfesor.setMaximumSize(null);
        btnAgregarProfesor.setMinimumSize(new java.awt.Dimension(103, 23));
        btnAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 140, -1));
        getContentPane().add(txtAgProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 120, -1));

        btnAgregarTutor.setText("Agregar Tutor");
        btnAgregarTutor.setMaximumSize(null);
        btnAgregarTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTutorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 140, -1));

        btnAgregarCotutor.setText("Agregar Cotutor");
        btnAgregarCotutor.setMaximumSize(null);
        btnAgregarCotutor.setMinimumSize(new java.awt.Dimension(103, 23));
        btnAgregarCotutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCotutorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCotutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 140, -1));

        btnAgregarJurado.setText("Agregar Jurado");
        btnAgregarJurado.setMaximumSize(null);
        btnAgregarJurado.setMinimumSize(new java.awt.Dimension(103, 23));
        btnAgregarJurado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJuradoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarJurado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 140, -1));

        btnAgregarAlumno.setText("Agregar Alumno");
        btnAgregarAlumno.setMaximumSize(null);
        btnAgregarAlumno.setMinimumSize(new java.awt.Dimension(103, 23));
        btnAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 140, -1));
        getContentPane().add(txtAgTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 223, 120, -1));
        getContentPane().add(txtAgCotutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 120, -1));
        getContentPane().add(txtAgJurado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 120, -1));

        txtAgAlumno.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtAgAlumno.setMinimumSize(new java.awt.Dimension(60, 20));
        getContentPane().add(txtAgAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 130, -1));
        getContentPane().add(txtApProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 130, -1));
        txtApProf.setVisible(false);

        jLabel10.setText("Nombre");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 173, 80, -1));

        jLabel11.setText("Apellido");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 173, 80, -1));
        getContentPane().add(txtApTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 223, 130, -1));
        getContentPane().add(txtApCotutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 130, -1));
        getContentPane().add(txtApJurado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 130, -1));
        getContentPane().add(txtApAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 130, -1));

        jLabel12.setText("Nombre");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 80, -1));

        jLabel13.setText("Apellido");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 80, -1));

        jLabel14.setText("Nombre");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 285, 60, -1));

        jLabel15.setText("Apellido");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 285, 60, -1));

        jLabel16.setText("Nombre");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 325, 60, -1));

        jLabel17.setText("Apellido");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 325, 60, -1));

        jLabel18.setText("Nombre");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 245, 60, -1));

        jLabel19.setText("Apellido");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 245, 60, -1));

        jPanel1.setBackground(new java.awt.Color(255, 214, 11));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Fecha de presentacion");
        jPanel1.add(jLabel2);
        jPanel1.add(fechaPre);

        jLabel3.setText("Fecha de aprobacion");
        jPanel1.add(jLabel3);
        jPanel1.add(fechaAp);

        jLabel4.setText("Fecha de exposicion");
        jPanel1.add(jLabel4);
        jPanel1.add(fechaEx);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 320, 150));

        jPanel2.setBackground(new java.awt.Color(255, 214, 21));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 150));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
//        
//        if (btnGuardar.getText().equalsIgnoreCase("Guardar")) {
//            activaDesactiva(true);
//            btnGuardar.setText("Guarda");
//        } else
        if (txtTitulo.getText().equalsIgnoreCase("") || txtDuracion.getText().equalsIgnoreCase("") || txtArea.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Debe llenarse los campos");
        } else {
            trabajo.setTitulo(txtTitulo.getText());
            trabajo.setDuracion(txtDuracion.getText());
            trabajo.setAreas(txtArea.getText());
            trabajo.setFechaPresentacion(dateFormat.format(fechaPre.getDate()));
            trabajo.setFechaAprobacion(dateFormat.format(fechaAp.getDate()));
            trabajo.setFechaExposicion(dateFormat.format(fechaEx.getDate()));
            trabajo.setProfesor((String) comboProfesor.getSelectedItem());
            trabajo.setTutor((String) comboTutor.getSelectedItem());
            trabajo.setCotutor((String) comboCotutor.getSelectedItem());
            trabajo.setJurado((String) comboJurado.getSelectedItem());
            trabajo.setAlumno((String) comboAlumno.getSelectedItem());

            gt.guardar(trabajo);
            gt.guardarArchivo(trabajo);

            JOptionPane.showMessageDialog(this, "Guardado con exito");
            btnGuardar.setText("Guardar");
            limpiar();
            activaDesactiva(false);

        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Desea volver al menu principal?", "Avertencia", JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {

            this.setVisible(false);
            JFrame frame = new Frm_Opciones();

            frame.setLocationRelativeTo(frame);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProfesorActionPerformed
        // TODO add your handling code here:
        if (btnAgregarProfesor.getText().equalsIgnoreCase("Agregar profesor")) {
            txtAgProf.setVisible(true);
            txtApProf.setVisible(true);
            btnAgregarProfesor.setText("Agregar");
            jLabel10.setVisible(true);
            jLabel11.setVisible(true);
        } else if (txtAgProf.getText().equalsIgnoreCase("") || txtApProf.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Escribir el nuevo profesor");
        } else {
            agregarAlCombo(txtAgProf.getText(), txtApProf.getText(), comboProfesor);
            Profesor a = new Profesor(txtApProf.getText(), txtAgProf.getText(), 0, null);
            profesores.add(a);
            txtAgProf.setVisible(false);
            txtApProf.setVisible(false);
            txtAgProf.setText("");
            txtApProf.setText("");
            btnAgregarProfesor.setText("Agregar Profesor");
            jLabel10.setVisible(false);
            jLabel11.setVisible(false);
        }
    }//GEN-LAST:event_btnAgregarProfesorActionPerformed

    private void btnAgregarJuradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJuradoActionPerformed
        // TODO add your handling code here:
        if (btnAgregarJurado.getText().equalsIgnoreCase("Agregar Jurado")) {
            txtAgJurado.setVisible(true);
            txtApJurado.setVisible(true);
            btnAgregarJurado.setText("Agregar");
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
        } else if (txtAgJurado.getText().equalsIgnoreCase("") || txtApJurado.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Escribir el nuevo jurado");
        } else {
            agregarAlCombo(txtAgJurado.getText(), txtApJurado.getText(), comboJurado);
            Profesor a = new Profesor(txtApJurado.getText(), txtAgJurado.getText(), 0, null);
            jurados.add(a);
            txtAgJurado.setVisible(false);
            txtApJurado.setVisible(false);
            txtAgJurado.setText("");
            txtApJurado.setText("");
            btnAgregarJurado.setText("Agregar jurado");
            jLabel14.setVisible(false);
            jLabel15.setVisible(false);
        }
    }//GEN-LAST:event_btnAgregarJuradoActionPerformed

    private void btnAgregarTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTutorActionPerformed
        // TODO add your handling code here:
        if (btnAgregarTutor.getText().equalsIgnoreCase("Agregar tutor")) {
            txtAgTutor.setVisible(true);
            txtApTutor.setVisible(true);
            btnAgregarTutor.setText("Agregar");
            jLabel12.setVisible(true);
            jLabel13.setVisible(true);
        } else if (txtAgTutor.getText().equalsIgnoreCase("") || txtApTutor.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Escribir el nuevo tutor");
        } else {
            agregarAlCombo(txtAgTutor.getText(), txtApTutor.getText(), comboTutor);
            Profesor a = new Profesor(txtApTutor.getText(), txtAgTutor.getText(), 0, null);
            tutores.add(a);
            txtAgTutor.setVisible(false);
            txtApTutor.setVisible(false);
            txtAgTutor.setText("");
            txtApTutor.setText("");
            btnAgregarTutor.setText("Agregar alumno");
            jLabel12.setVisible(false);
            jLabel13.setVisible(false);
        }


    }//GEN-LAST:event_btnAgregarTutorActionPerformed

    private void btnAgregarCotutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCotutorActionPerformed
        // TODO add your handling code here:
        if (btnAgregarCotutor.getText().equalsIgnoreCase("Agregar cotutor")) {
            txtAgCotutor.setVisible(true);
            txtApCotutor.setVisible(true);
            btnAgregarCotutor.setText("Agregar");
            jLabel18.setVisible(true);
            jLabel19.setVisible(true);
        } else if (txtAgCotutor.getText().equalsIgnoreCase("") || txtApCotutor.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Escribir el nuevo cotutor");
        } else {
            agregarAlCombo(txtAgCotutor.getText(), txtApCotutor.getText(), comboCotutor);
            Profesor a = new Profesor(txtApProf.getText(), txtAgProf.getText(), 0, null);
            cotutores.add(a);
            txtAgCotutor.setVisible(false);
            txtApCotutor.setVisible(false);
            txtAgCotutor.setText("");
            txtApCotutor.setText("");
            btnAgregarCotutor.setText("Agregar cotutor");
            jLabel18.setVisible(false);
            jLabel19.setVisible(false);
        }

    }//GEN-LAST:event_btnAgregarCotutorActionPerformed

    private void btnAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoActionPerformed
        // TODO add your handling code here:
        if (btnAgregarAlumno.getText().equalsIgnoreCase("Agregar alumno")) {
            txtAgAlumno.setVisible(true);
            txtApAlumno.setVisible(true);
            btnAgregarAlumno.setText("Agregar");
            jLabel16.setVisible(true);
            jLabel17.setVisible(true);
        } else if (txtAgAlumno.getText().equalsIgnoreCase("") || txtApAlumno.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Escribir el nuevo alumno");
        } else {
            agregarAlCombo(txtAgAlumno.getText(), txtApAlumno.getText(), comboAlumno);

            Alumno a = new Alumno(txtApAlumno.getText(), txtAgAlumno.getText(), 0, null);
            alumnos.add(a);
            txtAgAlumno.setVisible(false);
            txtApAlumno.setVisible(false);
            txtAgAlumno.setText("");
            txtApAlumno.setText("");
            btnAgregarAlumno.setText("Agregar alumno");
            jLabel16.setVisible(false);
            jLabel17.setVisible(false);
        }
    }//GEN-LAST:event_btnAgregarAlumnoActionPerformed

    public void agregarAlCombo(String profe, String apellido, JComboBox combo) {
        Profesor a = new Profesor(apellido, profe, 0, null);
        combo.addItem(a.getNombres() + " " + a.getApellidos());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_GuardarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_GuardarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_GuardarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_GuardarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_GuardarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Area;
    private javax.swing.JLabel Duracion;
    private javax.swing.JButton btnAgregarAlumno;
    private javax.swing.JButton btnAgregarCotutor;
    private javax.swing.JButton btnAgregarJurado;
    private javax.swing.JButton btnAgregarProfesor;
    private javax.swing.JButton btnAgregarTutor;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboAlumno;
    private javax.swing.JComboBox<String> comboCotutor;
    public static javax.swing.JComboBox<String> comboJurado;
    public static javax.swing.JComboBox<String> comboProfesor;
    private javax.swing.JComboBox<String> comboTutor;
    public static com.toedter.calendar.JDateChooser fechaAp;
    private com.toedter.calendar.JDateChooser fechaEx;
    private com.toedter.calendar.JDateChooser fechaPre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAgAlumno;
    private javax.swing.JTextField txtAgCotutor;
    private javax.swing.JTextField txtAgJurado;
    private javax.swing.JTextField txtAgProf;
    private javax.swing.JTextField txtAgTutor;
    private javax.swing.JTextField txtApAlumno;
    private javax.swing.JTextField txtApCotutor;
    private javax.swing.JTextField txtApJurado;
    private javax.swing.JTextField txtApProf;
    private javax.swing.JTextField txtApTutor;
    public static javax.swing.JTextField txtArea;
    public static javax.swing.JTextField txtDuracion;
    public static javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
